"""Synthesizer — materialize a schema-valid scenario YAML from a catalog technique.

Deterministic by design (Q2 answer): the *creativity* lives in the planner (which
techniques, what order); the synthesizer only assembles a vetted attack from the
catalog entry and refuses anything unsafe. It NEVER writes inline shell — it references
only existing ``scripts/vm/`` scripts. Guards, in order:

  1. catalog entry exists and ``status == implemented``;
  2. ``reference_script`` is set and exists on disk under scripts/vm/;
  3. every ``setup_scripts`` entry exists on disk;
  4. destructive ⇒ ``safe_target`` present; ``requires_testdata`` ⇒ setup_scripts non-empty;
  5. target resource is inside the campaign scope (hard allowlist);
  6. the produced YAML validates against the scenario schema.

A failure yields ``SynthesisResult(ok=False, reason=...)`` — the scenario is not written.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from annatar.campaign.scope import Scope
from annatar.runner.parser import ScenarioParser

# Repo root = parents[2] of annatar/campaign/synthesizer.py
REPO_ROOT = Path(__file__).resolve().parents[2]

# Detection-window margin added on top of the catalog's P99 latency.
_LATENCY_MARGIN_S = 120


@dataclass
class SynthesisResult:
    ok: bool
    reason: str = ""
    path: Path | None = None
    scenario: dict | None = None


def _slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "scenario"


def _script_exists(rel: str) -> bool:
    return (REPO_ROOT / rel).is_file()


def _rg_and_vm(resource_id: str) -> tuple[str, str]:
    parts = resource_id.split("/")
    rg = vm = ""
    for i, p in enumerate(parts):
        if p.lower() == "resourcegroups" and i + 1 < len(parts):
            rg = parts[i + 1]
    if parts:
        vm = parts[-1]
    return rg, vm


def synthesize(
    *,
    entry: dict[str, Any],
    target_resource_id: str,
    scope: Scope,
    out_dir: str | Path,
    seq: int = 1,
    allow_destructive: bool = False,
) -> SynthesisResult:
    """Materialize one scenario YAML for ``entry`` against ``target_resource_id``.

    ``entry`` is a technique-catalog entry (with ``resource_type`` merged in).
    ``out_dir`` is the campaign ``scenarios/`` directory.
    """
    ttp = entry.get("ttp", "")

    # 1. implemented-only
    if entry.get("status") != "implemented":
        return SynthesisResult(False, f"{ttp}: status != implemented — not synthesizable")

    # 2/3. scripts must exist on disk (no inline shell, ever)
    ref = entry.get("reference_script")
    if not ref:
        return SynthesisResult(False, f"{ttp}: no reference_script")
    if not _script_exists(ref):
        return SynthesisResult(False, f"{ttp}: reference_script not found: {ref}")
    setup_scripts = list(entry.get("setup_scripts") or [])
    for s in setup_scripts:
        if not _script_exists(s):
            return SynthesisResult(False, f"{ttp}: setup_script not found: {s}")

    # 4. destructive guardrail
    destructive = bool(entry.get("destructive"))
    safe_target = entry.get("safe_target") or ""
    if destructive:
        if not allow_destructive:
            return SynthesisResult(False, f"{ttp}: destructive but budget.allow_destructive is false")
        if not safe_target:
            return SynthesisResult(False, f"{ttp}: destructive without safe_target — refused")
        if entry.get("requires_testdata") and not setup_scripts:
            return SynthesisResult(
                False, f"{ttp}: requires_testdata but no setup_scripts to provision it"
            )

    # 5. scope (hard allowlist)
    rg, vm = _rg_and_vm(target_resource_id)
    guard = scope.check(target_resource_id, rg)
    if not guard.allowed:
        return SynthesisResult(False, f"{ttp}: out of scope — {guard.reason}")
    if not vm:
        return SynthesisResult(False, f"{ttp}: cannot derive vm_name from {target_resource_id}")

    # ── build the scenario dict (schema: name/description/mitre/target/steps) ──
    latency = int(entry.get("expected_latency_s") or 300)
    timeout_s = latency + _LATENCY_MARGIN_S
    name = entry.get("name", ttp)
    scenario: dict[str, Any] = {
        "name": f"campaign-{_slug(ttp)}-{_slug(name)}"[:80],
        "description": f"{ttp} — {name} (generated by Annatar campaign — proposition)",
        "mitre": ttp,
        "version": "1.0.0",
        "target": {
            # Schema currently only admits azure_vm; Storage/Entra targets need a
            # schema extension before they become synthesizable (catalog notes this).
            "type": "azure_vm",
            "resource_group": rg,
            "vm_name": vm,
        },
        "steps": [
            {
                "name": f"execute-{_slug(ttp)}",
                "action": "run_script_on_vm",
                "script": ref,
                "record": "T0",
            }
        ],
        "detection": {
            "timeout": f"{timeout_s}s",
            "hints": _build_hints(entry),
        },
    }
    if setup_scripts:
        scenario["setup"] = [
            {
                "name": f"setup-{i}-{Path(s).stem}",
                "action": "run_script_on_vm",
                "script": s,
            }
            for i, s in enumerate(setup_scripts, 1)
        ]

    # normalize target.type: schema currently only allows azure_vm
    scenario["target"]["type"] = "azure_vm"

    # 6. write + final schema validation
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    fname = f"{seq:02d}-{ttp}-{_slug(name)}.yaml"
    path = out / fname
    path.write_text(
        yaml.safe_dump(
            scenario, sort_keys=False, default_flow_style=False, allow_unicode=True
        )
    )

    res = ScenarioParser().validate(str(path))
    if not res.valid:
        path.unlink(missing_ok=True)
        return SynthesisResult(False, f"{ttp}: produced YAML failed schema: {res.errors}")

    return SynthesisResult(True, path=path, scenario=scenario)


def _build_hints(entry: dict[str, Any]) -> dict[str, Any]:
    """Build detection.hints from the catalog blue block (feeds propose_detection_rule
    only if the attack is MISSED — Annatar's own scenario metadata, not an announcement)."""
    cols = entry.get("indicator_columns") or []
    hints: dict[str, Any] = {
        "log_source": entry.get("log_source", ""),
        "attack_commands_summary": (
            f"Generated campaign step for {entry.get('ttp')} "
            f"({entry.get('name', '')}) via {entry.get('reference_script')}."
        ),
    }
    if cols:
        src = entry.get("log_source", "")
        hints["expected_indicators"] = [f"{src}: column {c}" for c in cols]
    return hints
